name: stackblue
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  flutter_bluetooth_serial: ^0.4.0
  provider: ^6.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  sensors_plus: ^6.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
